commerce/auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("add", views.add, name="add"),
    path("listing/<id>", views.listing_view, name="listing"),
    path("bid", views.add_bid, name="add_bid"),
    path("watchlist/<id>", views.add_to_watchlist, name="add_to_watchlist"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("close/<id>", views.close, name="close"),
    path("comment", views.comment, name="comment"),
    path("categories", views.categories, name="categories"),
    path("category/<name>", views.category, name="category"),
]

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.timezone import now


class User(AbstractUser):
    id = models.AutoField(primary_key=True)

    watchlist = models.ManyToManyField('Listing', related_name="watchers")


class Listing(models.Model):
    id = models.AutoField(primary_key=True)

    title = models.CharField(max_length=64)
    description = models.TextField()
    starting_bid = models.IntegerField()
    image_url = models.URLField(null=True, blank=True, max_length=400)
    category = models.CharField(max_length=64, null=True, blank=True)
    active = models.BooleanField(default=True)
    time = models.DateTimeField(default=now)

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="listings")


class Bid(models.Model):
    id = models.AutoField(primary_key=True)

    value = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bids")
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="bids")


class Comment(models.Model):
    id = models.AutoField(primary_key=True)

    text = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="comments")
 

commerce/auctions/forms.py
from django.forms import ModelForm, Textarea, URLInput, TextInput, NumberInput, URLField, CharField

from .models import User, Listing, Bid, Comment

class AddListingForm(ModelForm):
    image_url = URLField(required=False, 
                         widget=URLInput(attrs={"class": "form-control", 
                                                "placeholder": "Image",},))
    category = CharField(required=False, 
                         widget=TextInput(attrs={"class": "form-control", 
                                         "placeholder": "Category",}))

    class Meta:
        model = Listing
        fields = ["title", "description", "starting_bid", "image_url", "category", "user"]

        widgets = {
            "title": TextInput(attrs={"class": "form-control", 
                                      "placeholder": "Title",}),
            "description": Textarea(attrs={"class": "form-control", 
                                           "placeholder": "Description",}),
            "starting_bid": NumberInput(attrs={"class": "form-control", 
                                               "placeholder": "Starting Bid",}),
        }


class AddBidForm(ModelForm):
    class Meta:
        model = Bid
        fields = ["value", "listing", "user",]

        widgets = {
            "value": TextInput(attrs={"class": "form-control",
                                      "placeholder": "Bid"}),
        }


class AddCommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["text", "listing", "user"]

        widgets = {
            "text": Textarea(attrs={"class": "form-control",
                                      "placeholder": "Comment",
                                      "rows": 5,
                                      "cols": 20}),
        }

commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout, decorators
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages

from . import utils 
from .forms import AddListingForm, AddBidForm, AddCommentForm
from .models import User, Listing


def index(request):
    listings = []
    raw_listings = Listing.objects.all()

    for listing in raw_listings:
        listings.append(utils.produce_listing(request.user, listing))

    listings.sort(key=lambda listing: listing["listing"].id)
    listings.reverse()

    return render(request, "auctions/index.html", {
        "listings": listings,
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            messages.error(request, "Invalid username and/or password.")
            return render(request, "auctions/login.html")
    else:
        return render(request, "auctions/login.html")


@decorators.login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            messages.error(request, "Passwords must match.")
            return render(request, "auctions/register.html")

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            messages.error(request, "Username already taken.")
            return render(request, "auctions/register.html")
        
        login(request, user)

        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")
    

@decorators.login_required
def add(request):
    if request.method != "POST":
        return render(request, "auctions/add.html", {
            "form": AddListingForm
        })

    form = AddListingForm(request.POST)
    
    if form.is_valid():

        form.save()

        messages.success(request, 'Listing created successfully')
        return HttpResponseRedirect(reverse("index"))

    messages.error(request, "New listing invalid.")
    return render(request, "auctions/add.html", {
            "form": form
        })


def listing_view(request, id):
    listing = utils.produce_listing(request.user, Listing.objects.get(id=id))
    output = {
        "bid_form": AddBidForm,
        "comment_form": AddCommentForm,
        "num_bids": len(listing["listing"].bids.all()),
        "comments": listing["listing"].comments.all(),
    }
    output.update(listing)

    return render(request, "auctions/listing.html", output)
    

@decorators.login_required
def add_bid(request):
    if request.method != "POST":
        return HttpResponseRedirect(reverse("index"))
    
    form = AddBidForm(request.POST)

    if form.is_valid():
        bid = form.cleaned_data

        current_price = utils.get_top_bid(bid["listing"])[0]

        if (bid["value"] > current_price
                or (bid["value"] == bid["listing"].starting_bid and current_price == bid["listing"].starting_bid)):
            form.save()

            messages.success(request, "Bid added successfully")
        else:
            messages.error(request, "Bid must be above the current bid")

        return HttpResponseRedirect(reverse("listing", args=[bid["listing"].id,]))

    else:
        messages.error(request, "Bid invalid")

    return HttpResponseRedirect(reverse("index"))


@decorators.login_required
def add_to_watchlist(request, id):
    # Add or remove item from user's watchlist
    listing = Listing.objects.get(id=id)

    if listing not in request.user.watchlist.all():
        request.user.watchlist.add(listing)
        messages.success(request, "Listing added to watchlist")
    else:
        request.user.watchlist.remove(listing)
        messages.info(request, "Listing removed from watchlist")

    return HttpResponseRedirect(reverse("listing", args=[id]))


@decorators.login_required
def watchlist(request):
    listings = []
    raw_listings = Listing.objects.all()

    for l in raw_listings:
        new_listing = utils.produce_listing(request.user, l)

        if new_listing["watchlisted"]:
            listings.append(new_listing)

    listings.sort(key=lambda l: l["listing"].id)
    listings.reverse()

    return render(request, "auctions/watchlist.html", {
        "listings": listings
    })


@decorators.login_required
def close(request, id):
    listing = Listing.objects.get(id=id)

    if listing.user == request.user:
        listing.active = False
        listing.save()
        messages.warning(request, "Listing closed successfully")
    else:
        messages.error(request, "You are not the owner of this listing")
    
    return HttpResponseRedirect(reverse("listing", args=[id,]))


@decorators.login_required
def comment(request):
    if request.method != "POST":
        return HttpResponseRedirect(reverse("index"))

    form = AddCommentForm(request.POST)

    if form.is_valid():
        form.save()

        messages.success(request, "Comment added successfully")
        return HttpResponseRedirect(reverse("listing", args=[form.cleaned_data["listing"].id]))

    messages.error(request, "Comment invalid")
    try:
        return HttpResponseRedirect(reverse("listing", args=[form.cleaned_data["listing"].id]))
    except:
        return HttpResponseRedirect(reverse("index"))


def categories(request):
    return render(request, "auctions/categories.html", {
        "categories": utils.get_categories(request.user),
    })


def category(request, name):
    try:
        category = next(c for c in utils.get_categories(request.user) if c["name"] == name)
    except StopIteration:
        return HttpResponseRedirect(reverse("categories"))

    return render(request, "auctions/category.html", {
        "category": category,
    })

commerce/auctions/templates/auctions/add.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2 class="my-3">Create Listing</h2>

    <div class="col-lg-5">
        <form action="{% url 'add' %}" method="post" class="form">
            {% csrf_token %}
            <div class="my-3">
                {{ form.title }}
            </div>

            <div class="my-3">
                {{ form.description }}
            </div>

            <div class="my-3">
                {{ form.starting_bid }}
            </div>

            <div class="my-3">
                {{ form.image_url }}
            </div>

            <div class="my-3">
                {{ form.category}}
            </div>
            <input type="hidden" name="user" id="id_user" value="{{ user.id }}">
            <input type="submit" class="form-input btn btn-primary">
        </form>
    </div>

{% endblock %}

commerce/auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h1>
        <b>Categories:</b>
    </h1>

    <hr>
    {% for category in categories %}
        <a href="{% url "category" category.name %}"><h2>{{ category.name }}</h2></a>
        <p class="small">{{ category.size }} items</p>

        <hr>
    {% endfor %}

{% endblock %}

commerce/auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2 class="mt-3"><b>Category:</b> {{ category.name }}</h2>
    <hr>

    {% for listing in category.listings %}
        {% if listing.listing.active %}
            <div class="listing-row row">
                <!-- Image -->
                <div class="col-md-4">
                    <div class="d-flex align-items-center">
                        {% if listing.listing.image_url %}
                            <img class="listing-img mx-auto" src="{{listing.listing.image_url}}" alt="Image for listing: {{listing.listing.title}}">
                        {% else %}
                            <h2 class="mx-auto">No image found</h2>
                        {% endif %}
                    </div>
                </div>
                <!-- Text -->
                <div class="col-md-8">
                    <!-- Title -->
                    <a href="{% url 'listing' listing.listing.id %}">
                        <h5>{{listing.listing.title}}</h5>
                    </a>

                    <!-- Badges -->
                    <div>
                        {% if listing.listing.user == user %}
                            <span class="badge badge-success">Yours</span>
                        {% endif %}
                        {% if listing.watchlisted %}
                            <span class="badge badge-primary">Watchlist</span>
                        {% endif %}
                    </div>

                    <!-- Description -->
                    <div>
                        <p>{{listing.listing.description}}</p>
                    </div>

                    <!-- Category -->
                    <div>
                        <p><Strong>Category: </Strong>{% if listing.listing.category %} {{listing.listing.category}} {% else %} None {% endif %}</p>
                    </div>
                    <!-- Price -->
                    <div>
                        <p><Strong>Current price: </Strong>{{listing.price}}</p>
                    </div>
                    <div class="small">Created on {{listing.listing.time}}</div>
                </div>
            </div>
            <hr>
        {% endif %}
    {% endfor %}
    
{% endblock %}

commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2 class="mx-auto mt-3">Active Listings</h2>
    <hr>

    {% for listing in listings %}
        {% if listing.listing.active %}
            <div class="listing-row row">
                <!-- Image -->
                <div class="col-md-4">
                    <div class="d-flex align-items-center">
                        {% if listing.listing.image_url %}
                            <img class="listing-img mx-auto" src="{{listing.listing.image_url}}" alt="Image for listing: {{listing.listing.title}}">
                        {% else %}
                            <h2 class="mx-auto">No image found</h2>
                        {% endif %}
                    </div>
                </div>
                <!-- Text -->
                <div class="col-md-8">
                    <!-- Title -->
                    <a href="{% url 'listing' listing.listing.id %}">
                        <h5>{{listing.listing.title}}</h5>
                    </a>

                    <!-- Badges -->
                    <div>
                        {% if listing.listing.user == user %}
                            <span class="badge badge-success">Yours</span>
                        {% endif %}
                        {% if listing.watchlisted %}
                            <span class="badge badge-primary">Watchlist</span>
                        {% endif %}
                    </div>

                    <!-- Description -->
                    <div>
                        <p>{{listing.listing.description}}</p>
                    </div>

                    <!-- Category -->
                    <div>
                        <p><Strong>Category: </Strong>{% if listing.listing.category %} {{listing.listing.category}} {% else %} None {% endif %}</p>
                    </div>
                    <!-- Price -->
                    <div>
                        <p><Strong>Current price: </Strong>{{listing.price}}</p>
                    </div>
                    <div class="small">Created on {{listing.listing.time}}</div>
                </div>
            </div>
            <hr>
        {% endif %}
    {% endfor %}
    
{% endblock %}

commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>

        <h1 class="mx-3">Auctions</h1>

        <div class="mx-3">
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>

        <nav class="navbar border-bottom">
            <div class="container-fluid">
    
                <div class="expand navbar-expand">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'add' %}">Create Listing</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'watchlist' %}">Watchlist</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'categories' %}">Categories</a>
                        </li>
                    </ul>
                </div>
                <div class="expand navbar-expand">
                    <ul class="navbar-nav">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'login' %}">Log In</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'register' %}">Register</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% if messages %}
            <div class="messages mt-3">
                {% for message in messages %}
                    <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% else %} class="alert alert-primary" {% endif %}>{{ message }}</div>
                {% endfor %}
            </div>
        {% endif %}
        <div class="mx-3">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

commerce/auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block body %}
    <div class="mx-3">
        <!-- Title -->
        <div class="row mt-3">
            <h1>
                <b>Listing:</b> {{listing.title}}
            </h1>
        </div>
        
        <!-- Badges -->
        <div class="row">
            {% if not listing.active %}
                <span class="badge badge-warning mx-1">Closed</span> 
                {% if top_bid.user == user %}
                    <span class="badge badge-success mx-1">Won</span>
                {% endif %}
            {% endif %}

            {% if user.is_authenticated %}
                {% if listing.user == user %} 
                    <span class="badge badge-success mx-1">Yours</span>
                {% endif %}

                <a href="{% url 'add_to_watchlist' listing.id %}"
                    {% if watchlisted %}
                        class="badge badge-secondary">Remove from watchlist
                    {% else %}
                        class="badge badge-primary">Add to watchlist
                    {% endif %}
                </a>
            {% endif %}
        </div>

        <!-- Image -->
        <div class="row mt-3">
            {% if listing.image_url %}
                <img class="listing-img" src="{{listing.image_url}}" alt="Image for listing: {{listing.title}}">
            {% endif %}
        </div>
        <hr>

        <!-- Description -->
        <div class="row mt-1">
            <p class="fs-3">{{listing.description}}</p>
        </div>

        <!-- Price -->
        <div class="row">
            <h2>{{price}}</h2>
        </div>
        <div class="row">
            <div class="small font-weight-bold">
                {% if listing.active %}
                    {{num_bids}} bid(s). 
                    {% if top_bid %}
                        {% if top_bid.user.id == user.id %}Your bid is the current bid.{% endif %}
                    {% endif %}
                {% else %} 
                    This listing is closed. 
                    {% if top_bid %}
                        {% if top_bid.user.id == user.id %}You have won the auction.{% endif %}
                    {% endif %}
                {% endif %}
                {% if user == listing.user %} 
                    This is your listing.
                {% endif %}
            </div>
        </div>

        {% if user.is_authenticated and listing.active%}
            <div class="row">
                {% if user != listing.user%}
                    <!-- Place bid -->
                        <form action="{% url 'add_bid' %}" method="post" class="col-md-12 mt-1">
                            {% csrf_token %}

                            <div class="row">
                                <div class="col-md-3">
                                    {{ bid_form.value }}
                                </div>
                                <div class="col-md-3">
                                    <input type="submit" class="form-input btn btn-primary" value="Place Bid">
                                </div>
                            </div>

                            <input type="hidden" name="user" id="id_user" value="{{ user.id }}">
                            <input type="hidden" name="listing" id="id_listing" value="{{ listing.id }}">

                        </form>

                {% else %}
                    <!-- Close listing button -->
                    <a href="{% url 'close' listing.id %}" class="btn btn-warning mt-3">Close listing</a>

                {% endif %}
            </div>
        {% endif %}

        <!-- Details -->
        <div class="row mt-3">
            <p><b>Details: </b></p>
            <ul>
                <li><b>Category: </b>{{listing.category}}</li>
                <li><b>Seller: </b>{{listing.user}}</li>
                <li><b>Created: </b>{{listing.time}}</li>
            </ul>
        </div>

        <!-- Comments -->
        <hr>
        <div class="row mt-3">
                <h3>Comments: </h3>
        </div>
        <div class="row mt-3">
            <span class="border col-md-6">
                <form action="{% url 'comment' %}" method="post" class="m-3">
                    <h5>New comment:</h5>
                    {% csrf_token %}

                    <div class="row">
                        {{ comment_form.text }}
                    </div>
                    <div class="row">
                        <input type="submit" class="form-input btn btn-primary mt-1" value="Comment">
                    </div>

                    <input type="hidden" name="user" id="id_user" value="{{ user.id }}">
                    <input type="hidden" name="listing" id="id_listing" value="{{ listing.id }}">
                </form>
            </span>
        </div>
        {% if comments %}
            {% for comment in comments %}
                <div class="row mt-3">
                    <span class="border col-md-6">
                        <h5 class="mt-3">
                            {{ comment.user }}:
                        </h5>

                        <p>
                            {{ comment.text }}
                        </p>
                    </span>
                </div>
            {% endfor %}
        {% else %}
            <h5>No comments yet</h5>
        {% endif %}
    </div>
{% endblock %}1

commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

commerce/auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h1>Watchlist</h1>
    <hr>

    {% for listing in listings %}
        <div class="listing-row row">
            <!-- Image -->
            <div class="col-md-4">
                <div class="d-flex align-items-center">
                    {% if listing.listing.image_url %}
                        <img class="listing-img mx-auto" src="{{listing.listing.image_url}}" alt="Image for listing: {{listing.listing.title}}">
                    {% else %}
                        <h2 class="mx-auto">No image found</h2>
                    {% endif %}
                </div>
            </div>
            <!-- Text -->
            <div class="col-md-8">
                <!-- Title -->
                <a href="{% url 'listing' listing.listing.id %}">
                    <h5>{{listing.listing.title}}</h5>
                </a>

                <!-- Badges -->
                <div>
                    {% if listing.listing.user == user %}
                        <span class="badge badge-success">Yours</span>
                    {% endif %}
                    {% if not listing.listing.active %}
                        <span class="badge badge-warning">Closed</span>
                    {% endif %}
                </div>

                <!-- Description -->
                <div>
                    <p>{{listing.listing.description}}</p>
                </div>

                <!-- Category -->
                <div>
                    <p><Strong>Category: </Strong>{% if listing.listing.category %} {{listing.listing.category}} {% else %} None {% endif %}</p>
                </div>
                <!-- Price -->
                <div>
                    <p><Strong>Current price: </Strong>{{listing.price}}</p>
                </div>
            </div>
        </div>
        <hr>
    {% endfor %}
{% endblock %}